Adjust committing dist

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -58,7 +58,7 @@ jobs:
       - name: Run unit tests
         run: npm run test:ci
 
-  build:
+  build-and-commit-dist:
     runs-on: ubuntu-latest
     needs:
       - lint
@@ -77,22 +77,19 @@ jobs:
       - name: Build project
         run: npm run build
 
-  commit-dist:
-    runs-on: ubuntu-latest
-    needs:
-      - build
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
       - name: Check if dist directory has changed
         id: check-dist-changes
         run: |
-          if git diff --quiet HEAD "${{ github.event.before }}" -- ./dist; then
+          if git diff --quiet HEAD "${{ github.event.before }}" -- ./dist 2>/dev/null; then
             echo "No changes detected in the dist directory."
           else
             echo "dist_changed=true" >> "$GITHUB_ENV"
-          fi || echo "Failed to check git diff on dist directory changes."
+          fi
+
+          if [ $? -ne 0 ]; then
+            echo "Could not check diffs from the last commit"
+            echo "This cloud be caused by initial commit on this branch.
+          fi
 
       - name: Commit dist and types if changed
         if: steps.check-dist-changes.outputs.dist_changed == 'true'
