Changed command back and added just a fail fallback

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -42,16 +42,11 @@ jobs:
       - name: Check if dist directory has changed
         id: check-dist-changes
         run: |
-          before_commit="${{ github.event.before }}"
-          if git cat-file -e "$before_commit"; then
-            if git diff --quiet HEAD "$before_commit" -- ./dist; then
-              echo "No changes detected in the dist directory."
-            else
-              echo "dist_changed=true" >> "$GITHUB_ENV"
-            fi
-          else
-            echo "Invalid commit SHA: $before_commit"
-          fi
+           if git diff --quiet HEAD "${{ github.event.before }}" -- ./dist; then
+             echo "No changes detected in the dist directory."
+           else
+             echo "dist_changed=true" >> "$GITHUB_ENV"
+           fi || echo "Failed to check git diff on dist directory changes."
 
       - name: Commit dist and types if changed
         if: steps.check-dist-changes.outputs.dist_changed == 'true'
