Split up jobs for better overview description

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -2,16 +2,9 @@ name: Build
 on: [push]
 
 jobs:
-  build:
+  install-and-cache-deps:
     runs-on: ubuntu-latest
-    env:
-      CI_COMMIT_MESSAGE: "Continuous Integration Build Project"
-      CI_COMMIT_AUTHOR: "${{ github.event.repository.name }} Continuous Integration"
-
     steps:
-      - name: Display event name
-        run: echo "github.event_name=${{ github.event_name }}"
-
       - name: Checkout repository
         uses: actions/checkout@v4
 
@@ -21,7 +14,7 @@ jobs:
           node-version: 20
 
       - name: Cache node modules
-        uses: actions/cache@v4
+        uses: actions/cache@v2
         with:
           path: node_modules
           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
@@ -30,23 +23,54 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
+  lint:
+    runs-on: ubuntu-latest
+    needs: install-and-cache-deps
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Install dependencies
+        run: npm ci
+
       - name: Lint project
         run: npm run lint
 
-      - name: Build project
-        run: npm run build
+  test:
+    runs-on: ubuntu-latest
+    needs: install-and-cache-deps
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
       - name: Run unit tests
         run: npm run test:ci
 
+  build:
+    runs-on: ubuntu-latest
+    needs: [lint, test, install-and-cache-deps]
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Build project
+        run: npm run build
+
+  commit-dist:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
       - name: Check if dist directory has changed
         id: check-dist-changes
         run: |
-           if git diff --quiet HEAD "${{ github.event.before }}" -- ./dist; then
-             echo "No changes detected in the dist directory."
-           else
-             echo "dist_changed=true" >> "$GITHUB_ENV"
-           fi || echo "Failed to check git diff on dist directory changes."
+          if git diff --quiet HEAD "${{ github.event.before }}" -- ./dist; then
+            echo "No changes detected in the dist directory."
+          else
+            echo "dist_changed=true" >> "$GITHUB_ENV"
+          fi || echo "Failed to check git diff on dist directory changes."
 
       - name: Commit dist and types if changed
         if: steps.check-dist-changes.outputs.dist_changed == 'true'
